/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095;

import localhost9095.controllers.*;
import localhost9095.http.client.HttpClient;

public class ApiDocumentationClient {
    /**
     * Singleton access to Advantages controller
     * @return	Returns the AdvantagesController instance 
     */
    public AdvantagesController getAdvantages() {
        return AdvantagesController.getInstance();
    }

    /**
     * Singleton access to Demo controller
     * @return	Returns the DemoController instance 
     */
    public DemoController getDemo() {
        return DemoController.getInstance();
    }

    /**
     * Singleton access to SaveTestData controller
     * @return	Returns the SaveTestDataController instance 
     */
    public SaveTestDataController getSaveTestData() {
        return SaveTestDataController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public ApiDocumentationClient() {
    }

}