/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import localhost9095.*;
import localhost9095.models.*;
import localhost9095.exceptions.*;
import localhost9095.http.client.HttpClient;
import localhost9095.http.client.HttpContext;
import localhost9095.http.request.HttpRequest;
import localhost9095.http.response.HttpResponse;
import localhost9095.http.response.HttpStringResponse;
import localhost9095.http.client.APICallBack;
import localhost9095.controllers.syncwrapper.APICallBackCatcher;

public class AdvantagesController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static AdvantagesController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the AdvantagesController class 
     */
    public static AdvantagesController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new AdvantagesController();
                }
            }
        }
        return instance;
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     * @return    Returns the ClaimsDisbursementModel response from the API call 
     */
    public ClaimsDisbursementModel fetchSecondLevelOfInheritanceBranch1UsingGET(
                final int id
    ) throws Throwable {

        HttpRequest _request = _buildFetchSecondLevelOfInheritanceBranch1UsingGETRequest(id);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleFetchSecondLevelOfInheritanceBranch1UsingGETResponse(_context);
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     */
    public void fetchSecondLevelOfInheritanceBranch1UsingGETAsync(
                final int id,
                final APICallBack<ClaimsDisbursementModel> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildFetchSecondLevelOfInheritanceBranch1UsingGETRequest(id);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            ClaimsDisbursementModel returnValue = _handleFetchSecondLevelOfInheritanceBranch1UsingGETResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for fetchSecondLevelOfInheritanceBranch1UsingGET
     */
    private HttpRequest _buildFetchSecondLevelOfInheritanceBranch1UsingGETRequest(
                final int id) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/beta/claims/disbursement/{id}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("id", id);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for fetchSecondLevelOfInheritanceBranch1UsingGET
     * @return An object of type ClaimsDisbursementModel
     */
    private ClaimsDisbursementModel _handleFetchSecondLevelOfInheritanceBranch1UsingGETResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("Unauthorized", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Forbidden", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("Not Found", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        ClaimsDisbursementModel _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<ClaimsDisbursementModel>(){});

        return _result;
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     * @return    Returns the MaturityDisbursementModel response from the API call 
     */
    public MaturityDisbursementModel fetchSecondLevelOfInheritanceBranch2UsingGET(
                final int id
    ) throws Throwable {

        HttpRequest _request = _buildFetchSecondLevelOfInheritanceBranch2UsingGETRequest(id);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleFetchSecondLevelOfInheritanceBranch2UsingGETResponse(_context);
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     */
    public void fetchSecondLevelOfInheritanceBranch2UsingGETAsync(
                final int id,
                final APICallBack<MaturityDisbursementModel> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildFetchSecondLevelOfInheritanceBranch2UsingGETRequest(id);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            MaturityDisbursementModel returnValue = _handleFetchSecondLevelOfInheritanceBranch2UsingGETResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for fetchSecondLevelOfInheritanceBranch2UsingGET
     */
    private HttpRequest _buildFetchSecondLevelOfInheritanceBranch2UsingGETRequest(
                final int id) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/beta/maturity/disbursement/{id}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("id", id);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for fetchSecondLevelOfInheritanceBranch2UsingGET
     * @return An object of type MaturityDisbursementModel
     */
    private MaturityDisbursementModel _handleFetchSecondLevelOfInheritanceBranch2UsingGETResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("Unauthorized", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Forbidden", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("Not Found", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        MaturityDisbursementModel _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<MaturityDisbursementModel>(){});

        return _result;
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     * @return    Returns the DisbursementPayeeModel response from the API call 
     */
    public DisbursementPayeeModel fetchFirstLevelOfInheritanceUsingGET(
                final int id
    ) throws Throwable {

        HttpRequest _request = _buildFetchFirstLevelOfInheritanceUsingGETRequest(id);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleFetchFirstLevelOfInheritanceUsingGETResponse(_context);
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     */
    public void fetchFirstLevelOfInheritanceUsingGETAsync(
                final int id,
                final APICallBack<DisbursementPayeeModel> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildFetchFirstLevelOfInheritanceUsingGETRequest(id);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            DisbursementPayeeModel returnValue = _handleFetchFirstLevelOfInheritanceUsingGETResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for fetchFirstLevelOfInheritanceUsingGET
     */
    private HttpRequest _buildFetchFirstLevelOfInheritanceUsingGETRequest(
                final int id) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/beta/payee/disbursement/{id}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("id", id);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for fetchFirstLevelOfInheritanceUsingGET
     * @return An object of type DisbursementPayeeModel
     */
    private DisbursementPayeeModel _handleFetchFirstLevelOfInheritanceUsingGETResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("Unauthorized", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Forbidden", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("Not Found", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        DisbursementPayeeModel _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<DisbursementPayeeModel>(){});

        return _result;
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     * @return    Returns the PayeePaymentModel response from the API call 
     */
    public PayeePaymentModel fetchOnlyOneTableUsingGET(
                final int id
    ) throws Throwable {

        HttpRequest _request = _buildFetchOnlyOneTableUsingGETRequest(id);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleFetchOnlyOneTableUsingGETResponse(_context);
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     */
    public void fetchOnlyOneTableUsingGETAsync(
                final int id,
                final APICallBack<PayeePaymentModel> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildFetchOnlyOneTableUsingGETRequest(id);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            PayeePaymentModel returnValue = _handleFetchOnlyOneTableUsingGETResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for fetchOnlyOneTableUsingGET
     */
    private HttpRequest _buildFetchOnlyOneTableUsingGETRequest(
                final int id) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/beta/payment/payee/{id}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("id", id);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for fetchOnlyOneTableUsingGET
     * @return An object of type PayeePaymentModel
     */
    private PayeePaymentModel _handleFetchOnlyOneTableUsingGETResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("Unauthorized", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Forbidden", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("Not Found", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        PayeePaymentModel _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<PayeePaymentModel>(){});

        return _result;
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     * @return    Returns the SalaryDisbursementModel response from the API call 
     */
    public SalaryDisbursementModel fetchSecondLevelOfInheritanceBranch3UsingGET(
                final int id
    ) throws Throwable {

        HttpRequest _request = _buildFetchSecondLevelOfInheritanceBranch3UsingGETRequest(id);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleFetchSecondLevelOfInheritanceBranch3UsingGETResponse(_context);
    }

    /**
     * This approach is the test of building models based on model self-aware approach
     * @param    id    Required parameter: id
     */
    public void fetchSecondLevelOfInheritanceBranch3UsingGETAsync(
                final int id,
                final APICallBack<SalaryDisbursementModel> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildFetchSecondLevelOfInheritanceBranch3UsingGETRequest(id);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            SalaryDisbursementModel returnValue = _handleFetchSecondLevelOfInheritanceBranch3UsingGETResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for fetchSecondLevelOfInheritanceBranch3UsingGET
     */
    private HttpRequest _buildFetchSecondLevelOfInheritanceBranch3UsingGETRequest(
                final int id) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/beta/salary/disbursement/{id}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("id", id);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for fetchSecondLevelOfInheritanceBranch3UsingGET
     * @return An object of type SalaryDisbursementModel
     */
    private SalaryDisbursementModel _handleFetchSecondLevelOfInheritanceBranch3UsingGETResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //Error handling using HTTP status codes
        int _responseCode = _response.getStatusCode();

        if (_responseCode == 401) {
            throw new APIException("Unauthorized", _context);
        }
        if (_responseCode == 403) {
            throw new APIException("Forbidden", _context);
        }
        if (_responseCode == 404) {
            throw new APIException("Not Found", _context);
        }
        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        SalaryDisbursementModel _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<SalaryDisbursementModel>(){});

        return _result;
    }

}
