/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class ClaimsDisbursementModelBuilder {
    //the instance to build
    private ClaimsDisbursementModel claimsDisbursementModel;

    /**
     * Default constructor to initialize the instance
     */
    public ClaimsDisbursementModelBuilder() {
        claimsDisbursementModel = new ClaimsDisbursementModel();
    }

    public ClaimsDisbursementModelBuilder amount(Integer amount) {
        claimsDisbursementModel.setAmount(amount);
        return this;
    }

    public ClaimsDisbursementModelBuilder bankCode(String bankCode) {
        claimsDisbursementModel.setBankCode(bankCode);
        return this;
    }

    public ClaimsDisbursementModelBuilder bankName(String bankName) {
        claimsDisbursementModel.setBankName(bankName);
        return this;
    }

    public ClaimsDisbursementModelBuilder claimId(String claimId) {
        claimsDisbursementModel.setClaimId(claimId);
        return this;
    }

    public ClaimsDisbursementModelBuilder claimType(String claimType) {
        claimsDisbursementModel.setClaimType(claimType);
        return this;
    }

    public ClaimsDisbursementModelBuilder disbursementId(Integer disbursementId) {
        claimsDisbursementModel.setDisbursementId(disbursementId);
        return this;
    }

    public ClaimsDisbursementModelBuilder disbursementMethod(String disbursementMethod) {
        claimsDisbursementModel.setDisbursementMethod(disbursementMethod);
        return this;
    }

    public ClaimsDisbursementModelBuilder firstName(String firstName) {
        claimsDisbursementModel.setFirstName(firstName);
        return this;
    }

    public ClaimsDisbursementModelBuilder payeeId(String payeeId) {
        claimsDisbursementModel.setPayeeId(payeeId);
        return this;
    }

    public ClaimsDisbursementModelBuilder paymentId(Integer paymentId) {
        claimsDisbursementModel.setPaymentId(paymentId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ClaimsDisbursementModel build() {
        return claimsDisbursementModel;
    }
}