/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class CoursesByUniversityBuilder {
    //the instance to build
    private CoursesByUniversity coursesByUniversity;

    /**
     * Default constructor to initialize the instance
     */
    public CoursesByUniversityBuilder() {
        coursesByUniversity = new CoursesByUniversity();
    }

    /**
     * This refers to the field name course_entity.descr
     */
    public CoursesByUniversityBuilder courseDescr(String courseDescr) {
        coursesByUniversity.setCourseDescr(courseDescr);
        return this;
    }

    /**
     * This refers to the field name university_entity.descr
     */
    public CoursesByUniversityBuilder univDescr(String univDescr) {
        coursesByUniversity.setUnivDescr(univDescr);
        return this;
    }

    /**
     * This refers to the field name university_entity.name
     */
    public CoursesByUniversityBuilder universityName(String universityName) {
        coursesByUniversity.setUniversityName(universityName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CoursesByUniversity build() {
        return coursesByUniversity;
    }
}