/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class DisbursementPayeeModelBuilder {
    //the instance to build
    private DisbursementPayeeModel disbursementPayeeModel;

    /**
     * Default constructor to initialize the instance
     */
    public DisbursementPayeeModelBuilder() {
        disbursementPayeeModel = new DisbursementPayeeModel();
    }

    public DisbursementPayeeModelBuilder amount(Integer amount) {
        disbursementPayeeModel.setAmount(amount);
        return this;
    }

    public DisbursementPayeeModelBuilder bankCode(String bankCode) {
        disbursementPayeeModel.setBankCode(bankCode);
        return this;
    }

    public DisbursementPayeeModelBuilder bankName(String bankName) {
        disbursementPayeeModel.setBankName(bankName);
        return this;
    }

    public DisbursementPayeeModelBuilder disbursementId(Integer disbursementId) {
        disbursementPayeeModel.setDisbursementId(disbursementId);
        return this;
    }

    public DisbursementPayeeModelBuilder disbursementMethod(String disbursementMethod) {
        disbursementPayeeModel.setDisbursementMethod(disbursementMethod);
        return this;
    }

    public DisbursementPayeeModelBuilder firstName(String firstName) {
        disbursementPayeeModel.setFirstName(firstName);
        return this;
    }

    public DisbursementPayeeModelBuilder payeeId(String payeeId) {
        disbursementPayeeModel.setPayeeId(payeeId);
        return this;
    }

    public DisbursementPayeeModelBuilder paymentId(Integer paymentId) {
        disbursementPayeeModel.setPaymentId(paymentId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DisbursementPayeeModel build() {
        return disbursementPayeeModel;
    }
}