/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class MaturityDisbursementModelBuilder {
    //the instance to build
    private MaturityDisbursementModel maturityDisbursementModel;

    /**
     * Default constructor to initialize the instance
     */
    public MaturityDisbursementModelBuilder() {
        maturityDisbursementModel = new MaturityDisbursementModel();
    }

    public MaturityDisbursementModelBuilder amount(Integer amount) {
        maturityDisbursementModel.setAmount(amount);
        return this;
    }

    public MaturityDisbursementModelBuilder bankCode(String bankCode) {
        maturityDisbursementModel.setBankCode(bankCode);
        return this;
    }

    public MaturityDisbursementModelBuilder bankName(String bankName) {
        maturityDisbursementModel.setBankName(bankName);
        return this;
    }

    public MaturityDisbursementModelBuilder disbursementId(Integer disbursementId) {
        maturityDisbursementModel.setDisbursementId(disbursementId);
        return this;
    }

    public MaturityDisbursementModelBuilder disbursementMethod(String disbursementMethod) {
        maturityDisbursementModel.setDisbursementMethod(disbursementMethod);
        return this;
    }

    public MaturityDisbursementModelBuilder firstName(String firstName) {
        maturityDisbursementModel.setFirstName(firstName);
        return this;
    }

    public MaturityDisbursementModelBuilder maturityId(String maturityId) {
        maturityDisbursementModel.setMaturityId(maturityId);
        return this;
    }

    public MaturityDisbursementModelBuilder maturityType(String maturityType) {
        maturityDisbursementModel.setMaturityType(maturityType);
        return this;
    }

    public MaturityDisbursementModelBuilder maturityValid(String maturityValid) {
        maturityDisbursementModel.setMaturityValid(maturityValid);
        return this;
    }

    public MaturityDisbursementModelBuilder payeeId(String payeeId) {
        maturityDisbursementModel.setPayeeId(payeeId);
        return this;
    }

    public MaturityDisbursementModelBuilder paymentId(Integer paymentId) {
        maturityDisbursementModel.setPaymentId(paymentId);
        return this;
    }

    public MaturityDisbursementModelBuilder remarks(String remarks) {
        maturityDisbursementModel.setRemarks(remarks);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MaturityDisbursementModel build() {
        return maturityDisbursementModel;
    }
}