/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class PayeePaymentModelBuilder {
    //the instance to build
    private PayeePaymentModel payeePaymentModel;

    /**
     * Default constructor to initialize the instance
     */
    public PayeePaymentModelBuilder() {
        payeePaymentModel = new PayeePaymentModel();
    }

    public PayeePaymentModelBuilder bankCode(String bankCode) {
        payeePaymentModel.setBankCode(bankCode);
        return this;
    }

    public PayeePaymentModelBuilder bankName(String bankName) {
        payeePaymentModel.setBankName(bankName);
        return this;
    }

    public PayeePaymentModelBuilder firstName(String firstName) {
        payeePaymentModel.setFirstName(firstName);
        return this;
    }

    public PayeePaymentModelBuilder payeeId(String payeeId) {
        payeePaymentModel.setPayeeId(payeeId);
        return this;
    }

    public PayeePaymentModelBuilder paymentId(Integer paymentId) {
        payeePaymentModel.setPaymentId(paymentId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PayeePaymentModel build() {
        return payeePaymentModel;
    }
}