/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PayeePaymentModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = -7665663107591158608L;
    private String bankCode;
    private String bankName;
    private String firstName;
    private String payeeId;
    private Integer paymentId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bankCode")
    public String getBankCode ( ) { 
        return this.bankCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bankCode")
    public void setBankCode (String value) { 
        this.bankCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bankName")
    public String getBankName ( ) { 
        return this.bankName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bankName")
    public void setBankName (String value) { 
        this.bankName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("firstName")
    public String getFirstName ( ) { 
        return this.firstName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("firstName")
    public void setFirstName (String value) { 
        this.firstName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("payeeId")
    public String getPayeeId ( ) { 
        return this.payeeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("payeeId")
    public void setPayeeId (String value) { 
        this.payeeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentId")
    public Integer getPaymentId ( ) { 
        return this.paymentId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentId")
    public void setPaymentId (Integer value) { 
        this.paymentId = value;
    }
 
}
