/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class SalaryDisbursementModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2919844359235545257L;
    private Integer amount;
    private String bankCode;
    private String bankName;
    private String bonusStatus;
    private Integer disbursementId;
    private String disbursementMethod;
    private String firstName;
    private String payeeId;
    private Integer paymentId;
    private String remarks;
    private String salaryApproved;
    private String salaryId;
    private String salaryType;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("amount")
    public Integer getAmount ( ) { 
        return this.amount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("amount")
    public void setAmount (Integer value) { 
        this.amount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bankCode")
    public String getBankCode ( ) { 
        return this.bankCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bankCode")
    public void setBankCode (String value) { 
        this.bankCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bankName")
    public String getBankName ( ) { 
        return this.bankName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bankName")
    public void setBankName (String value) { 
        this.bankName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bonusStatus")
    public String getBonusStatus ( ) { 
        return this.bonusStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bonusStatus")
    public void setBonusStatus (String value) { 
        this.bonusStatus = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disbursementId")
    public Integer getDisbursementId ( ) { 
        return this.disbursementId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disbursementId")
    public void setDisbursementId (Integer value) { 
        this.disbursementId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disbursementMethod")
    public String getDisbursementMethod ( ) { 
        return this.disbursementMethod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disbursementMethod")
    public void setDisbursementMethod (String value) { 
        this.disbursementMethod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("firstName")
    public String getFirstName ( ) { 
        return this.firstName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("firstName")
    public void setFirstName (String value) { 
        this.firstName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("payeeId")
    public String getPayeeId ( ) { 
        return this.payeeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("payeeId")
    public void setPayeeId (String value) { 
        this.payeeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentId")
    public Integer getPaymentId ( ) { 
        return this.paymentId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentId")
    public void setPaymentId (Integer value) { 
        this.paymentId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("remarks")
    public String getRemarks ( ) { 
        return this.remarks;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("remarks")
    public void setRemarks (String value) { 
        this.remarks = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("salaryApproved")
    public String getSalaryApproved ( ) { 
        return this.salaryApproved;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("salaryApproved")
    public void setSalaryApproved (String value) { 
        this.salaryApproved = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("salaryId")
    public String getSalaryId ( ) { 
        return this.salaryId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("salaryId")
    public void setSalaryId (String value) { 
        this.salaryId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("salaryType")
    public String getSalaryType ( ) { 
        return this.salaryType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("salaryType")
    public void setSalaryType (String value) { 
        this.salaryType = value;
    }
 
}
