/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class StudentsUnderCoursesBuilder {
    //the instance to build
    private StudentsUnderCourses studentsUnderCourses;

    /**
     * Default constructor to initialize the instance
     */
    public StudentsUnderCoursesBuilder() {
        studentsUnderCourses = new StudentsUnderCourses();
    }

    /**
     * This refers to the field name course_entity.descr
     */
    public StudentsUnderCoursesBuilder courseDescr(String courseDescr) {
        studentsUnderCourses.setCourseDescr(courseDescr);
        return this;
    }

    /**
     * This field refers to student_entity.course_name
     */
    public StudentsUnderCoursesBuilder courseName(String courseName) {
        studentsUnderCourses.setCourseName(courseName);
        return this;
    }

    /**
     * This field refers to student_entity.first_name
     */
    public StudentsUnderCoursesBuilder firstName(String firstName) {
        studentsUnderCourses.setFirstName(firstName);
        return this;
    }

    /**
     * This field refers to student_entity.id
     */
    public StudentsUnderCoursesBuilder id(Integer id) {
        studentsUnderCourses.setId(id);
        return this;
    }

    /**
     * This refers to the field name university_entity.descr
     */
    public StudentsUnderCoursesBuilder univDescr(String univDescr) {
        studentsUnderCourses.setUnivDescr(univDescr);
        return this;
    }

    /**
     * This refers to the field name university_entity.name
     */
    public StudentsUnderCoursesBuilder universityName(String universityName) {
        studentsUnderCourses.setUniversityName(universityName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StudentsUnderCourses build() {
        return studentsUnderCourses;
    }
}