/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class StudentModelWithJoinInfo 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3617024939662675474L;
    private String courseName;
    private Integer disbursementId;
    private String lastName;
    private String offeredBy;
    private String payeeId;
    /** GETTER
     * This refers to the value fetched from the table column CourseEntity.course_name
     */
    @JsonGetter("courseName")
    public String getCourseName ( ) { 
        return this.courseName;
    }
    
    /** SETTER
     * This refers to the value fetched from the table column CourseEntity.course_name
     */
    @JsonSetter("courseName")
    public void setCourseName (String value) { 
        this.courseName = value;
    }
 
    /** GETTER
     * This refers to the value fetched from the table column StudentEntity.id
     */
    @JsonGetter("disbursementId")
    public Integer getDisbursementId ( ) { 
        return this.disbursementId;
    }
    
    /** SETTER
     * This refers to the value fetched from the table column StudentEntity.id
     */
    @JsonSetter("disbursementId")
    public void setDisbursementId (Integer value) { 
        this.disbursementId = value;
    }
 
    /** GETTER
     * This refers to the value fetched from the table column StudentEntity.last_name. This is fetched only because of RootInfo annotation and field name
     */
    @JsonGetter("lastName")
    public String getLastName ( ) { 
        return this.lastName;
    }
    
    /** SETTER
     * This refers to the value fetched from the table column StudentEntity.last_name. This is fetched only because of RootInfo annotation and field name
     */
    @JsonSetter("lastName")
    public void setLastName (String value) { 
        this.lastName = value;
    }
 
    /** GETTER
     * This refers to the value fetched from the table column UniversityEntity.id
     */
    @JsonGetter("offeredBy")
    public String getOfferedBy ( ) { 
        return this.offeredBy;
    }
    
    /** SETTER
     * This refers to the value fetched from the table column UniversityEntity.id
     */
    @JsonSetter("offeredBy")
    public void setOfferedBy (String value) { 
        this.offeredBy = value;
    }
 
    /** GETTER
     * This refers to the value fetched from the table column StudentEntity.first_name
     */
    @JsonGetter("payeeId")
    public String getPayeeId ( ) { 
        return this.payeeId;
    }
    
    /** SETTER
     * This refers to the value fetched from the table column StudentEntity.first_name
     */
    @JsonSetter("payeeId")
    public void setPayeeId (String value) { 
        this.payeeId = value;
    }
 
}
