/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class StudentModelWithJoinInfoBuilder {
    //the instance to build
    private StudentModelWithJoinInfo studentModelWithJoinInfo;

    /**
     * Default constructor to initialize the instance
     */
    public StudentModelWithJoinInfoBuilder() {
        studentModelWithJoinInfo = new StudentModelWithJoinInfo();
    }

    /**
     * This refers to the value fetched from the table column CourseEntity.course_name
     */
    public StudentModelWithJoinInfoBuilder courseName(String courseName) {
        studentModelWithJoinInfo.setCourseName(courseName);
        return this;
    }

    /**
     * This refers to the value fetched from the table column StudentEntity.id
     */
    public StudentModelWithJoinInfoBuilder disbursementId(Integer disbursementId) {
        studentModelWithJoinInfo.setDisbursementId(disbursementId);
        return this;
    }

    /**
     * This refers to the value fetched from the table column StudentEntity.last_name. This is fetched only because of RootInfo annotation and field name
     */
    public StudentModelWithJoinInfoBuilder lastName(String lastName) {
        studentModelWithJoinInfo.setLastName(lastName);
        return this;
    }

    /**
     * This refers to the value fetched from the table column UniversityEntity.id
     */
    public StudentModelWithJoinInfoBuilder offeredBy(String offeredBy) {
        studentModelWithJoinInfo.setOfferedBy(offeredBy);
        return this;
    }

    /**
     * This refers to the value fetched from the table column StudentEntity.first_name
     */
    public StudentModelWithJoinInfoBuilder payeeId(String payeeId) {
        studentModelWithJoinInfo.setPayeeId(payeeId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StudentModelWithJoinInfo build() {
        return studentModelWithJoinInfo;
    }
}