/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;

public class StudentModelPlainBuilder {
    //the instance to build
    private StudentModelPlain studentModelPlain;

    /**
     * Default constructor to initialize the instance
     */
    public StudentModelPlainBuilder() {
        studentModelPlain = new StudentModelPlain();
    }

    /**
     * This refers to the value fetched from the table column CourseEntity.course_name
     */
    public StudentModelPlainBuilder courseName(String courseName) {
        studentModelPlain.setCourseName(courseName);
        return this;
    }

    /**
     * This refers to the value fetched from the table column UniversityEntity.id
     */
    public StudentModelPlainBuilder offeredBy(String offeredBy) {
        studentModelPlain.setOfferedBy(offeredBy);
        return this;
    }

    /**
     * This refers to the value fetched from the table column StudentEntity.first_name
     */
    public StudentModelPlainBuilder payeeId(String payeeId) {
        studentModelPlain.setPayeeId(payeeId);
        return this;
    }

    /**
     * This refers to the value fetched from the table column StudentEntity.id
     */
    public StudentModelPlainBuilder studentId(Integer studentId) {
        studentModelPlain.setStudentId(studentId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StudentModelPlain build() {
        return studentModelPlain;
    }
}