/*
 * ApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package localhost9095.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class StudentsUnderCourses 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5698769696881530582L;
    private String courseDescr;
    private String courseName;
    private String firstName;
    private Integer id;
    private String univDescr;
    private String universityName;
    /** GETTER
     * This refers to the field name course_entity.descr
     */
    @JsonGetter("courseDescr")
    public String getCourseDescr ( ) { 
        return this.courseDescr;
    }
    
    /** SETTER
     * This refers to the field name course_entity.descr
     */
    @JsonSetter("courseDescr")
    public void setCourseDescr (String value) { 
        this.courseDescr = value;
    }
 
    /** GETTER
     * This field refers to student_entity.course_name
     */
    @JsonGetter("courseName")
    public String getCourseName ( ) { 
        return this.courseName;
    }
    
    /** SETTER
     * This field refers to student_entity.course_name
     */
    @JsonSetter("courseName")
    public void setCourseName (String value) { 
        this.courseName = value;
    }
 
    /** GETTER
     * This field refers to student_entity.first_name
     */
    @JsonGetter("firstName")
    public String getFirstName ( ) { 
        return this.firstName;
    }
    
    /** SETTER
     * This field refers to student_entity.first_name
     */
    @JsonSetter("firstName")
    public void setFirstName (String value) { 
        this.firstName = value;
    }
 
    /** GETTER
     * This field refers to student_entity.id
     */
    @JsonGetter("id")
    public Integer getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * This field refers to student_entity.id
     */
    @JsonSetter("id")
    public void setId (Integer value) { 
        this.id = value;
    }
 
    /** GETTER
     * This refers to the field name university_entity.descr
     */
    @JsonGetter("univDescr")
    public String getUnivDescr ( ) { 
        return this.univDescr;
    }
    
    /** SETTER
     * This refers to the field name university_entity.descr
     */
    @JsonSetter("univDescr")
    public void setUnivDescr (String value) { 
        this.univDescr = value;
    }
 
    /** GETTER
     * This refers to the field name university_entity.name
     */
    @JsonGetter("universityName")
    public String getUniversityName ( ) { 
        return this.universityName;
    }
    
    /** SETTER
     * This refers to the field name university_entity.name
     */
    @JsonSetter("universityName")
    public void setUniversityName (String value) { 
        this.universityName = value;
    }
 
}
